   version: '3.8'

   services:
     db:
       image: postgres:latest
       environment:
         POSTGRES_DB: Шалыгин
         POSTGRES_USER: user
         POSTGRES_PASSWORD: password
       volumes:
         - ./init.sql:/docker-entrypoint-initdb.d/init.sql
       ports:
         - "5432:5432"

     app:
       build: ./app
       depends_on:
         - db
   
